import 'car_model.dart';

final List<Car> cars = [
  Car(
    name: "Brezza 2020",
    image: "assets/images/1car.jpg",
    category: "Cars",
    price: "₹2000/day",
    address: "Race Course",
    features: ["Petrol", "Manual", "5 Seater", "Air Conditioning"],
  ),
  Car(
    name: "Mahindra Scorpio 2014",
    image: "assets/images/2car.jpg",
    category: "XUVs",
    price: "₹2550/day",
    address: "Ramnath Para",
    features: ["Diesel", "Manual", "7 Seater", "Rear AC Vents"],
  ),
  Car(
    name: "Maruti Suzuki Ertiga",
    image: "assets/images/4car.jpg",
    category: "Vans",
    price: "₹3000/day",
    address: "Sahakar Road",
    features: ["Petrol", "Manual", "7 Seater", "ABS"],
  ),
  Car(
    name: "Hyundai Creta 2021",
    image: "assets/images/creta.jpg",
    category: "SUVs",
    price: "₹2800/day",
    address: "Satellite Chowk",
    features: ["Diesel", "Automatic", "5 Seater", "Rear Camera"],
  ),
  Car(
    name: "Kia Seltos 2020",
    image: "assets/images/8car.jpg",
    category: "SUVs",
    price: "₹2100/day",
    address: "Bhaktinagar Circle",
    features: ["Petrol", "Manual", "5 Seater", "Alloy Wheels"],
  ),
  Car(
    name: "Tata Nexon EV 2023",
    image: "assets/images/5car.jpg",
    category: "SUVs",
    price: "₹3000/day",
    address: "University Road",
    features: ["Electric", "Automatic", "5 Seater", "Fast Charging"],
  ),
  Car(
    name: "Innova Crysta 2021",
    image: "assets/images/7car.jpg",
    category: "XUVs",
    price: "₹2500/day",
    address: "Morbi Road",
    features: ["Diesel", "Manual", "7 Seater", "Dual Zone AC"],
  ),
  Car(
    name: "Volkswagen Polo TDI 2021",
    image: "assets/images/10car.jpg",
    category: "Cars",
    price: "₹2700/day",
    address: "Bhavnath Park",
    features: ["Diesel", "Manual", "5 Seater", "Air Conditioning"],
  ),
  Car(
    name: "Ford Ecosport 2016",
    image: "assets/images/9car.jpg",
    category: "SUVs",
    price: "₹2300/day",
    address: "Kotecha Chowk",
    features: ["Petrol", "Manual", "5 Seater", "Fog Lamps"],
  ),
];
