import 'car_model.dart';

final List<Car> cars = [
  Car(
    name: "Brezza 2020",
    image: "assets/images/1car.jpg",
    details: "143 Trips",
    category: "Cars",
    price: "₹2000/day",
    address: "Race Course • 9 Km",
  ),
  Car(
    name: "Mahindra Scorpio 2014",
    image: "assets/images/2car.jpg",
    details: "114 Trips",
    category: "XUVs",
    price: "₹2550/day",
    address: "Ramnath Para",
  ),
  Car(
    name: "Maruti Suzuki Ertiga",
    image: "assets/images/4car.jpg",
    details: "12 Trips",
    category: "Vans",
    price: "₹3000/day",
    address: "Sahakar Road",
  ),
  Car(
    name: "Hyundai Creta 2021",
    image: "assets/images/creta.jpg",
    details: "95 Trips",
    category: "SUVs",
    price: "₹2800/day",
    address: "Satellite Chowk",
  ),
  Car(
    name: "Kia Seltos 2020",
    image: "assets/images/8car.jpg",
    details: "13 Trips",
    category: "SUVs",
    price: "₹2100/day",
    address: "Bhaktinagar Circle",
  ),
  Car(
    name: "Tata Nexon EV 2023",
    image: "assets/images/5car.jpg",
    details: "15 Trips",
    category: "SUVs",
    price: "₹3000/day",
    address: "University Road",
  ),
  Car(
    name: "Innova Crysta 2021",
    image: "assets/images/7car.jpg",
    details: "75 Trips",
    category: "XUVs",
    price: "₹2500/day",
    address: "Morbi Road",
  ),
  Car(
    name: "Volkswagen Polo TDI 2021",
    image: "assets/images/10car.jpg",
    details: "50 Trips",
    category: "Cars",
    price: "₹2700/day",
    address: "Bhavnath Park",
  ),
  Car(
    name: "Ford Ecosport 2016",
    image: "assets/images/9car.jpg",
    details: "90 Trips",
    category: "SUVs",
    price: "₹2300/day",
    address: "Kotecha Chowk",
  ),
];
