// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEK6FeZILDUzZLPsFe-m5OROLS7RMasDc',
    appId: '1:136403017507:web:c7819df7360a56849eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    authDomain: 'carrentingapp18.firebaseapp.com',
    storageBucket: 'carrentingapp18.firebasestorage.app',
    measurementId: 'G-W9TVY8NZC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMdbONw2VTG1Xm0ZAkMGWlpuN-AG_XWs',
    appId: '1:136403017507:android:176c1d4aae806ed89eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    storageBucket: 'carrentingapp18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_q_hzsK2HUe3AihyjJ-NK1OlrrFQTMtw',
    appId: '1:136403017507:ios:43009c08f56dfc669eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    storageBucket: 'carrentingapp18.firebasestorage.app',
    androidClientId: '136403017507-qh07tvg7o43bf32cm4g57j47bsmvj80o.apps.googleusercontent.com',
    iosClientId: '136403017507-co8o4jlkao3rms5i7s7idl0a2g7v463c.apps.googleusercontent.com',
    iosBundleId: 'com.example.expressCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_q_hzsK2HUe3AihyjJ-NK1OlrrFQTMtw',
    appId: '1:136403017507:ios:43009c08f56dfc669eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    storageBucket: 'carrentingapp18.firebasestorage.app',
    androidClientId: '136403017507-qh07tvg7o43bf32cm4g57j47bsmvj80o.apps.googleusercontent.com',
    iosClientId: '136403017507-co8o4jlkao3rms5i7s7idl0a2g7v463c.apps.googleusercontent.com',
    iosBundleId: 'com.example.expressCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEK6FeZILDUzZLPsFe-m5OROLS7RMasDc',
    appId: '1:136403017507:web:f5b39fafe7ed8d189eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    authDomain: 'carrentingapp18.firebaseapp.com',
    storageBucket: 'carrentingapp18.firebasestorage.app',
    measurementId: 'G-ZD7LCPM0GQ',
  );
}
