// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEK6FeZILDUzZLPsFe-m5OROLS7RMasDc',
    appId: '1:136403017507:web:c874179be96032539eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    authDomain: 'carrentingapp18.firebaseapp.com',
    storageBucket: 'carrentingapp18.firebasestorage.app',
    measurementId: 'G-1EXRENBD7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMdbONw2VTG1Xm0ZAkMGWlpuN-AG_XWs',
    appId: '1:136403017507:android:98a24c0a92cab6679eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    storageBucket: 'carrentingapp18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_q_hzsK2HUe3AihyjJ-NK1OlrrFQTMtw',
    appId: '1:136403017507:ios:85db4ef11bd2216a9eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    storageBucket: 'carrentingapp18.firebasestorage.app',
    iosClientId: '136403017507-1l2r26q6rs85adbp364j3c6jctaq0cp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_q_hzsK2HUe3AihyjJ-NK1OlrrFQTMtw',
    appId: '1:136403017507:ios:85db4ef11bd2216a9eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    storageBucket: 'carrentingapp18.firebasestorage.app',
    iosClientId: '136403017507-1l2r26q6rs85adbp364j3c6jctaq0cp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEK6FeZILDUzZLPsFe-m5OROLS7RMasDc',
    appId: '1:136403017507:web:c7819df7360a56849eb696',
    messagingSenderId: '136403017507',
    projectId: 'carrentingapp18',
    authDomain: 'carrentingapp18.firebaseapp.com',
    storageBucket: 'carrentingapp18.firebasestorage.app',
    measurementId: 'G-W9TVY8NZC6',
  );
}
